FROM frengky/webstack:debug
LABEL maintainer="frengky.lim@gmail.com"

COPY supervisor.d/crond.tpl /etc/supervisor.d/
COPY supervisor.d/laravel-worker.tpl /etc/supervisor.d/
COPY nginx/laravel.debug.conf /etc/nginx/conf.d/default.conf

WORKDIR /app
EXPOSE 8080

COPY scripts/docker-entrypoint-laravel.debug.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
